# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omnihook < Formula
  desc "Global Git Hook Manager"
  homepage "https://github.com/vjayajv/omnihook"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vjayajv/omnihook/releases/download/v1.1.2/omnihook_1.1.2_darwin_amd64.tar.gz"
      sha256 "d056a037846faca86927771e85333e4fcfe2d13e3de27741e3b95b31f0f12e39"

      def install
        bin.install "omnihook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vjayajv/omnihook/releases/download/v1.1.2/omnihook_1.1.2_darwin_arm64.tar.gz"
      sha256 "a8ca7329e9a1c8df7b3eb63d2af5b93fc7fe20c89a67183a2bc3786f56ed6e18"

      def install
        bin.install "omnihook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vjayajv/omnihook/releases/download/v1.1.2/omnihook_1.1.2_linux_amd64.tar.gz"
        sha256 "a7774279ecdca64015157dabd729156b3d37bcc7011048ab1549ce3b79fa780e"

        def install
          bin.install "omnihook"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vjayajv/omnihook/releases/download/v1.1.2/omnihook_1.1.2_linux_arm64.tar.gz"
        sha256 "ae43c11f3218d784be4102b644a5a355e2a2f1d4ee3bc4c5339b646bebfe2c6c"

        def install
          bin.install "omnihook"
        end
      end
    end
  end
end
