# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omnihook < Formula
  desc "Global Git Hook Manager"
  homepage "https://github.com/vjayajv/omnihook"
  version "1.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vjayajv/omnihook/releases/download/v1.1.4/omnihook_1.1.4_darwin_amd64.tar.gz"
      sha256 "192697ba777a55112b9485087e545edb0da5e64a89e83479ead29e3783449fb4"

      def install
        bin.install "omnihook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vjayajv/omnihook/releases/download/v1.1.4/omnihook_1.1.4_darwin_arm64.tar.gz"
      sha256 "7f4e8175250793047321a6a4d807401e95c6610562e226b1284238e5a5cb7c27"

      def install
        bin.install "omnihook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vjayajv/omnihook/releases/download/v1.1.4/omnihook_1.1.4_linux_amd64.tar.gz"
        sha256 "1562880bb72351bb52fb0b9c76c7b85b91c4e7e716e163b93727b1e46533e2bf"

        def install
          bin.install "omnihook"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vjayajv/omnihook/releases/download/v1.1.4/omnihook_1.1.4_linux_arm64.tar.gz"
        sha256 "10cec547ea175c62b8066e4aa09a86a8e5a19dd125348d5f365bfa0ed81b33e2"

        def install
          bin.install "omnihook"
        end
      end
    end
  end
end
